apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world-1 
  namespace: mercury-desa 
spec:
  hosts:
  - hello-world-1 # interpreted as reviews.foo.svc.cluster.local
  http:
  - name: "hello-world-1"
    match:
    - uri:
        prefix: "/test"
    - uri:
        prefix: "/prueba"
        rewrite:
        uri: "/test"
    route:
    - destination:
        host: hello-world-2 # interpreted as reviews.foo.svc.cluster.local