apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world-1
  namespace: mercury-desa
spec:
  hosts:
  - hello-world-1
  http:
  - match:
    - uri:
        exact: /test/actuator
    rewrite:
        exact: /test/
    route:
    - destination:
        host: hello-world-1
  - match:
    - uri:
        exact: /test/
    route:
    - destination:
        host: hello-world-1