apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hello-world-1
spec:
  hosts:
  - "*"
  # gateways:
  # - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /test
    route:
    - destination:
        host: hello-world-1
        port:
          number: 8080