apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: to-hello-world-1
  namespace: mercury-desa
spec:
  host: hello-world-2 # interpreted as reviews.foo.svc.cluster.local
  # subsets:
  # - name: v1
  #   labels:
  #     version: v1
  # - name: v2
  #   labels:
  #     version: v2